### ISSUE TITLE
Move to the Fastify org

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify-csrf#20]
Hello! Tomas here, one of the maintainers of Fastify :)
Thank you for building this plugin!
We think this is very valuable, and we would love to have it inside our GitHub org, so we can offer official support for csrf.
Would you like to transfer this repository to https://github.com/fastify?
You will keep admin rights, and we'll help you out maintaining the plugin. We would also need publish access on npm.
Let me know what you think, thanks!

**Comment by Tarang11** [comment]
Big yes, why not.🙂

**Comment by delvedor** [comment]
Awesome! :)
Then the next steps are [transferring the repository](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository) to the [Fastify](https://github.com/fastify) org and then add me and @mcollina as [owners on npm](https://docs.npmjs.com/cli/owner).
Once you have done that, we can start working together on the code! 🎉

**Comment by Tarang11** [comment]
@delvedor, I don’t have the permission to create public repositories on fastify.

**Comment by delvedor** [comment]
@Tarang11 you should not create a new repository, but transfer this one instead.
As soon as you start the process, we'll get a notification and accept the transfer request.

See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

**Comment by Tarang11** [comment]
Steps that i am following.
Settings -> Transfer 
In Organization name -> fastify

**Comment by mcollina** [comment]
I've just invited you to the org, you should be able to transfer once you accept.

**Comment by Tarang11** [comment]
@mcollina, @delvedor ownership transferred.

**Comment by delvedor** [comment]
Great thanks!
