### ISSUE TITLE
TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by razr001** [fastify/fastify-csrf#41]
## 🐛 Bug Report

"TypeError: Cannot read property 'constructor' of undefined
  at Object.addHook (E:\\myserver\\node_modules\\fastify\\fastify.js:494:14)

## To Reproduce

```js
fastify.register(require('fastify-cookie'))
fastify.register(require('fastify-csrf'))
fastify.addHook('onRequest', fastify.csrfProtection)
```

## Your Environment

- *node version*: 12
- *fastify version*: >=3.14.0
- *os*: Windows

**Comment by simoneb** [comment]
Plugin registration happens asynchronously, try awaiting the csrf plugin registration

**Comment by razr001** [comment]
Thanks for the quick turnaroundIt works
